/*
 * This Java source file was generated by the Gradle 'init' task.
 */
 
//Eureka Client
package JoshA;


import org.springframework.boot.SpringApplication; 
import org.springframework.boot.autoconfigure.SpringBootApplication; 
import org.springframework.boot.builder.SpringApplicationBuilder; 
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;
import org.springframework.context.annotation.Bean;
import org.springframework.web.bind.annotation.RequestMapping; 
import org.springframework.web.bind.annotation.RestController;

import org.springframework.cloud.netflix.eureka.EnableEurekaClient;

import JoshA.DataBox.Fruit;

@SpringBootApplication
@EnableEurekaClient
@RestController
public class Main extends SpringBootServletInitializer{
    //To enable Eureka Client cloud configuration for app
    
    public static void main(String[] args){
        
        SpringApplication.run(Main.class, args); 
    }
    
    @RequestMapping(value = "/")  
    public String home(){   
        
        return "Eureka Client application"; 
    }
    
    @Override  protected SpringApplicationBuilder configure(SpringApplicationBuilder application){
        
        return application.sources(Main.class);
    }
}


//Make sure that Spring-EurekaServer-Build project which is our Eureka Server that we will register this Eureka Client is already running


//Enter the below URL on your browser to see front-end of the Eureka server that Eureka Client is egistered to
//http://localhost:8761/


//Enter the below URL on your browser to see the front-end of this Eureka Client
//http://localhost:8080/

